# Generated by Django 2.1.3 on 2018-11-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Агенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=255)),
                ('komnat', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('s', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=16)),
                ('mainimage', models.ImageField(upload_to='')),
                ('opisanie', models.TextField()),
                ('shirota', models.DecimalField(decimal_places=10, max_digits=13)),
                ('dolgota', models.DecimalField(decimal_places=10, max_digits=13)),
                ('date_n', models.DateField()),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Agent')),
            ],
            options={
                'verbose_name_plural': 'Объекты',
                'ordering': ['date_n'],
            },
        ),
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Районы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Typ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Типы объектов',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name_plural': 'Типы'},
        ),
        migrations.AddField(
            model_name='object',
            name='rayon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Rayon'),
        ),
        migrations.AddField(
            model_name='object',
            name='typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Typ'),
        ),
        migrations.AddField(
            model_name='object',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Types'),
        ),
    ]
