# Generated by Django 2.1.3 on 2018-11-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181106_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='object',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
