# Generated by Django 2.1.3 on 2018-12-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181121_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='mainimage',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
