# Generated by Django 2.1.3 on 2018-12-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181210_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='floor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='floors',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='komnat',
            field=models.IntegerField(null=True),
        ),
    ]
