# Generated by Django 2.1.3 on 2018-12-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181210_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='s',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
