# Generated by Django 2.1.3 on 2018-12-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181210_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='adres',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='date_n',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='dolgota',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='shirota',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=13, null=True),
        ),
    ]
