# Generated by Django 2.1.3 on 2018-12-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181210_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='s_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='s_ssilka',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
