# Generated by Django 2.1.3 on 2018-12-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181210_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='tel',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
